version: '3.8'
services:
  test-docker:
    image: sgb
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      update_config:
        parallelism: 2
        delay: 5s
    ports:
      - "3005:3005"